[package]
name = "rust-elm-architecture"
version = "0.1.0"
authors = ["Peter Stuart <peter@peterstuart.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "s"
lto = true

[dependencies]
js-sys = "0.3.51"
lazy_static = "1.4.0"
wasm-bindgen = "0.2.63"
web-sys = { version = "0.3.51", features = ["console", "Document", "Element", "HtmlElement", "HtmlInputElement", "InputEvent", "Text", "Window"] }

[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1.5"

[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
