name: Rust
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        
      - name: rustfmt (lib)
        run: cargo fmt -- --check
        
      - name: clippy (lib)
        run: cargo clippy -- -D warnings && cargo clippy --tests -- -D warnings
        
      - name: test (lib)
        run: cargo test

      - name: rustfmt (macros)
        run: cd macros && cargo fmt -- --check
        
      - name: clippy (macros)
        run: cd macros && cargo clippy -- -D warnings && cargo clippy --tests -- -D warnings

      - name: rustfmt (example)
        run: cd examples/basic && cargo fmt -- --check
        
      - name: clippy (example)
        run: cd examples/basic && cargo clippy -- -D warnings && cargo clippy --tests -- -D warnings
        
      - name: test (example)
        run: cd examples/basic && cargo test

      - name: build (example)
        run: cd examples/basic && wasm-pack build
